export const tableHeader = [
  "#",
  "Image",
  "Title",
  "Currency",
  "Currency Icon",
  "Network",
  "Network Icon",
  "Presale Mint Price",
  "Public Mint Price",
  "Max Items",
  "Created",
  "Status",
  "Action",
];
