export const SESSION = {
  SEND_LOGIN_CREDENTIALS: "SEND_LOGIN_CREDENTIALS",
};
export const COMMON = {
  RESET_FIELD: "RESET_FIELD",
};

export const EXCHANGE = {
  ADD_EXCHANGE: "ADD_EXCHANGE",
  LIST_EXCHANGE: "LIST_EXCHANGE",
};

export const NETWORK = {
  ADD_NETWORK: "ADD_NETWORK",
  LIST_NETWORK: "LIST_NETWORK",
};
