export const SESSION = {
  SEND_LOGIN_CREDENTIALS: "SEND_LOGIN_CREDENTIALS",
};
export const COMMON = {
  RESET_FIELD: "RESET_FIELD",
  DELETE_ROW: "DELETE_ROW",
  LOG_OUT: "LOG_OUT",
  NOTIFICATION_LIST: "NOTIFICATION_LIST",
};

export const EXCHANGE = {
  ADD_EXCHANGE: "ADD_EXCHANGE",
  LIST_EXCHANGE: "LIST_EXCHANGE",
  EDIT_EXCHANGE: "EDIT_EXCHANGE",
  DELETE_EXCHANGE: "DELETE_EXCHANGE",
  VIEW_EXCHANGE: "VIEW_EXCHANGE",
  UPDATE_EXCHANGE: "UPDATE_EXCHANGE",
  ALL_EXCHANGE: "ALL_EXCHANGE",
};

export const NETWORK = {
  ADD_NETWORK: "ADD_NETWORK",
  LIST_NETWORK: "LIST_NETWORK",
  EDIT_NETWORK: "EDIT_NETWORK",
  DELETE_NETWORK: "DELETE_NETWORK",
  VIEW_NETWORK: "VIEW_NETWORK",
  UPDATE_NETWORK: "UPDATE_NETWORK",
  ALL_NETWORK: "ALL_NETWORK",
};

export const VIDEOS = {
  ADD_VIDEOS: "ADD_VIDEOS",
  LIST_VIDEOS: "LIST_VIDEOS",
  EDIT_VIDEOS: "EDIT_VIDEOS",
  DELETE_VIDEOS: "DELETE_VIDEOS",
  VIEW_VIDEOS: "VIEW_VIDEOS",
  UPDATE_VIDEOS: "UPDATE_VIDEOS",
  ALL_VIDEOS: "ALL_VIDEOS",
};

export const USERS = {
  ADD_USERS: "ADD_USERS",
  LIST_USERS: "LIST_USERS",
  EDIT_USERS: "EDIT_USERS",
  DELETE_USERS: "DELETE_USERS",
  VIEW_USERS: "VIEW_USERS",
  UPDATE_USERS: "UPDATE_USERS",
  ALL_USERS: "ALL_USERS",
};

export const COINS = {
  ADD_COINS: "ADD_COINS",
  LIST_COINS: "LIST_COINS",
  EDIT_COINS: "EDIT_COINS",
  DELETE_COINS: "DELETE_COINS",
  VIEW_COINS: "VIEW_COINS",
  UPDATE_COINS: "UPDATE_COINS",
};

export const AUDIT = {
  ADD_AUDIT: "ADD_AUDIT",
  LIST_AUDIT: "LIST_AUDIT",
  EDIT_AUDIT: "EDIT_AUDIT",
  DELETE_AUDIT: "DELETE_AUDIT",
  VIEW_AUDIT: "VIEW_AUDIT",
  UPDATE_AUDIT: "UPDATE_AUDIT",
  ALL_AUDIT: "ALL_AUDIT",
};
export const CHART_PROVIDER = {
  ADD_CHART_PROVIDER: "ADD_CHART_PROVIDER",
  LIST_CHART_PROVIDER: "LIST_CHART_PROVIDER",
  EDIT_CHART_PROVIDER: "EDIT_CHART_PROVIDER",
  DELETE_CHART_PROVIDER: "DELETE_CHART_PROVIDER",
  VIEW_CHART_PROVIDER: "VIEW_CHART_PROVIDER",
  UPDATE_CHART_PROVIDER: "UPDATE_CHART_PROVIDER",
  ALL_CHART_PROVIDER: "ALL_CHART_PROVIDER",
};

export const COMMUNITY = {
  ADD_COMMUNITY: "ADD_COMMUNITY",
  LIST_COMMUNITY: "LIST_COMMUNITY",
  EDIT_COMMUNITY: "EDIT_COMMUNITY",
  DELETE_COMMUNITY: "DELETE_COMMUNITY",
  VIEW_COMMUNITY: "VIEW_COMMUNITY",
  UPDATE_COMMUNITY: "UPDATE_COMMUNITY",
  ALL_COMMUNITY: "ALL_COMMUNITY",
};

export const CHAT = {
  ADD_CHAT: "ADD_CHAT",
  LIST_CHAT: "LIST_CHAT",
  EDIT_CHAT: "EDIT_CHAT",
  DELETE_CHAT: "DELETE_CHAT",
  VIEW_CHAT: "VIEW_CHAT",
  UPDATE_CHAT: "UPDATE_CHAT",
  ALL_CHAT: "ALL_CHAT",
};

export const SOCIALS = {
  ADD_SOCIALS: "ADD_SOCIALS",
  LIST_SOCIALS: "LIST_SOCIALS",
  EDIT_SOCIALS: "EDIT_SOCIALS",
  DELETE_SOCIALS: "DELETE_SOCIALS",
  VIEW_SOCIALS: "VIEW_SOCIALS",
  UPDATE_SOCIALS: "UPDATE_SOCIALS",
  ALL_SOCIALS: "ALL_SOCIALS",
};

export const MENUCARD = {
  ADD_MENUCARD: "ADD_MENUCARD",
  LIST_MENUCARD: "LIST_MENUCARD",
  EDIT_MENUCARD: "EDIT_MENUCARD",
  DELETE_MENUCARD: "DELETE_MENUCARD",
  VIEW_MENUCARD: "VIEW_MENUCARD",
  UPDATE_MENUCARD: "UPDATE_MENUCARD",
  ALL_MENUCARD: "ALL_MENUCARD",
};

export const NFT_MARKETPLACES = {
  ADD_NFT_MARKETPLACES: "ADD_NFT_MARKETPLACES",
  LIST_NFT_MARKETPLACES: "LIST_NFT_MARKETPLACES",
  EDIT_NFT_MARKETPLACES: "EDIT_NFT_MARKETPLACES",
  DELETE_NFT_MARKETPLACES: "DELETE_NFT_MARKETPLACES",
  VIEW_NFT_MARKETPLACES: "VIEW_NFT_MARKETPLACES",
  UPDATE_NFT_MARKETPLACES: "UPDATE_NFT_MARKETPLACES",
  ALL_NFT_MARKETPLACES: "ALL_NFT_MARKETPLACES",
};

export const NFT_LISTINGS = {
  ADD_NFT_LISTINGS: "ADD_NFT_LISTINGS",
  LIST_NFT_LISTINGS: "LIST_NFT_LISTINGS",
  EDIT_NFT_LISTINGS: "EDIT_NFT_LISTINGS",
  DELETE_NFT_LISTINGS: "DELETE_NFT_LISTINGS",
  VIEW_NFT_LISTINGS: "VIEW_NFT_LISTINGS",
  UPDATE_NFT_LISTINGS: "UPDATE_NFT_LISTINGS",
  ALL_NFT_LISTINGS: "ALL_NFT_LISTINGS",
};

export const BADGES = {
  ADD_BADGES: "ADD_BADGES",
  LIST_BADGES: "LIST_BADGES",
  EDIT_BADGES: "EDIT_BADGES",
  DELETE_BADGES: "DELETE_BADGES",
  VIEW_BADGES: "VIEW_BADGES",
  UPDATE_BADGES: "UPDATE_BADGES",
  ALL_BADGES: "ALL_BADGES",
};

export const NFT_LISTINGS_CATEGORY = {
  ADD_NFT_LISTINGS_CATEGORY: "ADD_NFT_LISTINGS_CATEGORY",
  LIST_NFT_LISTINGS_CATEGORY: "LIST_NFT_LISTINGS_CATEGORY",
  EDIT_NFT_LISTINGS_CATEGORY: "EDIT_NFT_LISTINGS_CATEGORY",
  DELETE_NFT_LISTINGS_CATEGORY: "DELETE_NFT_LISTINGS_CATEGORY",
  VIEW_NFT_LISTINGS_CATEGORY: "VIEW_NFT_LISTINGS_CATEGORY",
  UPDATE_NFT_LISTINGS_CATEGORY: "UPDATE_NFT_LISTINGS_CATEGORY",
  ALL_NFT_LISTINGS_CATEGORY: "ALL_NFT_LISTINGS_CATEGORY",
};

export const NFT_LISTINGS_CURRENCY = {
  ADD_NFT_LISTINGS_CURRENCY: "ADD_NFT_LISTINGS_CURRENCY",
  LIST_NFT_LISTINGS_CURRENCY: "LIST_NFT_LISTINGS_CURRENCY",
  EDIT_NFT_LISTINGS_CURRENCY: "EDIT_NFT_LISTINGS_CURRENCY",
  DELETE_NFT_LISTINGS_CURRENCY: "DELETE_NFT_LISTINGS_CURRENCY",
  VIEW_NFT_LISTINGS_CURRENCY: "VIEW_NFT_LISTINGS_CURRENCY",
  UPDATE_NFT_LISTINGS_CURRENCY: "UPDATE_NFT_LISTINGS_CURRENCY",
  ALL_NFT_LISTINGS_CURRENCY: "ALL_NFT_LISTINGS_CURRENCY",
};

export const AIRDROPS = {
  ADD_AIRDROPS: "ADD_AIRDROPS",
  LIST_AIRDROPS: "LIST_AIRDROPS",
  EDIT_AIRDROPS: "EDIT_AIRDROPS",
  DELETE_AIRDROPS: "DELETE_AIRDROPS",
  VIEW_AIRDROPS: "VIEW_AIRDROPS",
  UPDATE_AIRDROPS: "UPDATE_AIRDROPS",
  ALL_AIRDROPS: "ALL_AIRDROPS",
};

export const EVENTS = {
  ADD_EVENTS: "ADD_EVENTS",
  LIST_EVENTS: "LIST_EVENTS",
  EDIT_EVENTS: "EDIT_EVENTS",
  DELETE_EVENTS: "DELETE_EVENTS",
  VIEW_EVENTS: "VIEW_EVENTS",
  UPDATE_EVENTS: "UPDATE_EVENTS",
  ALL_EVENTS: "ALL_EVENTS",
};

export const EVENTS_CATEGORY = {
  ADD_EVENTS_CATEGORY: "ADD_EVENTS_CATEGORY ",
  LIST_EVENTS_CATEGORY: "LIST_EVENTS_CATEGORY ",
  EDIT_EVENTS_CATEGORY: "EDIT_EVENTS_CATEGORY ",
  DELETE_EVENTS_CATEGORY: "DELETE_EVENTS_CATEGORY ",
  VIEW_EVENTS_CATEGORY: "VIEW_EVENTS_CATEGORY ",
  UPDATE_EVENTS_CATEGORY: "UPDATE_EVENTS_CATEGORY ",
  ALL_EVENTS_CATEGORY: "ALL_EVENTS_CATEGORY ",
};

export const EVENTS_REWARD_ADDRESS = {
  ADD_EVENTS_REWARD_ADDRESS: "ADD_EVENTS_REWARD_ADDRESS ",
  LIST_EVENTS_REWARD_ADDRESS: "LIST_EVENTS_REWARD_ADDRESS ",
  EDIT_EVENTS_REWARD_ADDRESS: "EDIT_EVENTS_REWARD_ADDRESS ",
  DELETE_EVENTS_REWARD_ADDRESS: "DELETE_EVENTS_REWARD_ADDRESS ",
  VIEW_EVENTS_REWARD_ADDRESS: "VIEW_EVENTS_REWARD_ADDRESS",
  UPDATE_EVENTS_REWARD_ADDRESS: "UPDATE_EVENTS_REWARD_ADDRESS ",
  ALL_EVENTS_REWARD_ADDRESS: "ALL_EVENTS_REWARD_ADDRESS ",
};
