export const SESSION = {
  SEND_LOGIN_CREDENTIALS: "SEND_LOGIN_CREDENTIALS",
};
export const COMMON = {
  RESET_FIELD: "RESET_FIELD",
};
export const HOME = {
  RECENTLY_ADDED: "RECENTLY_ADDED",
  BIGGEST_GAINERS: "BIGGEST_GAINERS",
  BIGGEST_LOOSERS: "BIGGEST_LOOSERS",
  FEATURED_COIN_LIST: "FEATURED_COIN_LIST",
};
