export const SESSION = {
  SEND_LOGIN_CREDENTIALS: "SEND_LOGIN_CREDENTIALS",
};
export const COMMON = {
  RESET_FIELD: "RESET_FIELD",
};
export const HOME = {
  RECENTLY_ADDED: "RECENTLY_ADDED",
  BIGGEST_GAINERS: "BIGGEST_GAINERS",
  BIGGEST_LOOSERS: "BIGGEST_LOOSERS",
  FEATURED_COIN_LIST: "FEATURED_COIN_LIST",
  CRYPTO_CURRENCIES_LIST: "CRYPTO_CURRENCIES_LIST",
  CRYPTO_CURRENCIES_NEW: "CRYPTO_CURRENCIES_NEW",
  CRYPTO_CURRENCIES_PRESALE: "CRYPTO_CURRENCIES_PRESALE",
  CRYPTO_CURRENCIES_TODAYS_BEST: "CRYPTO_CURRENCIES_TODAYS_BEST",
  CRYPTO_CURRENCIES_TAB: "CRYPTO_CURRENCIES_TAB",
};

export const COIN = {
  COIN_DETAIL_FIRST_BLOCK: "COIN_DETAIL_FIRST_BLOCK",
  COIN_OVERVIEW_BLOCK: "COIN_OVERVIEW_BLOCK",
  COIN_ABOUT_BLOCK: "COIN_ABOUT_BLOCK",
  COIN_ONLOAD_VERIFICATION: "COIN_ONLOAD_VERIFICATION",
};
