export const SESSION = {
  SEND_LOGIN_CREDENTIALS: "SEND_LOGIN_CREDENTIALS",
};
export const COMMON = {
  RESET_FIELD: "RESET_FIELD",
  //LATEST_NEWS: "LATEST_NEWS",
  TOPBAR_SEARCH: "TOPBAR_SEARCH",
  COIN_VOTE: "COIN_VOTE",
  RECENT_SEARCH: "RECENT_SEARCH",
  LATEST_NEWS_FEED: "LATEST_NEWS_FEED",
};

export const HOME = {
  RECENTLY_ADDED: "RECENTLY_ADDED",
  BIGGEST_GAINERS: "BIGGEST_GAINERS",
  BIGGEST_LOOSERS: "BIGGEST_LOOSERS",
  FEATURED_COIN_LIST: "FEATURED_COIN_LIST",
  TRENDING_COIN_LIST: "TRENDING_COIN_LIST",
  CRYPTO_CURRENCIES_LIST: "CRYPTO_CURRENCIES_LIST",
  CRYPTO_CURRENCIES_NEW: "CRYPTO_CURRENCIES_NEW",
  CRYPTO_CURRENCIES_PRESALE: "CRYPTO_CURRENCIES_PRESALE",
  CRYPTO_CURRENCIES_TODAYS_BEST: "CRYPTO_CURRENCIES_TODAYS_BEST",
  CRYPTO_CURRENCIES_TAB: "CRYPTO_CURRENCIES_TAB",
  MENU_CARDS: "MENU_CARDS",
  NFT_LISTINGS: "NFT_LISTINGS",
  VIDEO_LIST: "VIDEO_LIST",
  EVENTS_BLOCK: "EVENTS_BLOCK",
};

export const COIN = {
  COIN_DETAIL_FIRST_BLOCK: "COIN_DETAIL_FIRST_BLOCK",
  COIN_OVERVIEW_BLOCK: "COIN_OVERVIEW_BLOCK",
  COIN_ABOUT_BLOCK: "COIN_ABOUT_BLOCK",
  COIN_ONLOAD_VERIFICATION: "COIN_ONLOAD_VERIFICATION",
  COIN_SOCIAL_GRAPH: "COIN_SOCIAL_GRAPH",
  COIN_RATING_BLOCK: "COIN_RATING_BLOCK",
  COIN_HISTORICAL_DATA_BLOCK: "COIN_HISTORICAL_DATA_BLOCK",
  COIN_TODAYS_PRICE_BLOCK: "COIN_TODAYS_PRICE_BLOCK",
  COIN_COMMUNITY_BLOCK: "COIN_COMMUNITY_BLOCK",
  COIN_FAQ_BLOCK: "COIN_FAQ_BLOCK",
  COIN_PRICE_GRAPH_BLOCK: "COIN_PRICE_GRAPH_BLOCK",
  COIN_EVENTS_BLOCK: "COIN_EVENTS_BLOCK",
  COIN_PRESALE_BLOCK: "COIN_PRESALE_BLOCK",
  MOST_VISITED: "MOST_VISITED",
  NEWS_BLOCK: "NEWS_BLOCK",
};

export const COINS = {
  RECENTLY_ADDED: "RECENTLY_ADDED",
  BIGGEST_GAINERS: "BIGGEST_GAINERS",
  BIGGEST_LOOSERS: "BIGGEST_LOOSERS",
  FEATURED_COIN_LIST: "FEATURED_COIN_LIST",
  CRYPTO_CURRENCIES_LIST: "CRYPTO_CURRENCIES_LIST",
  CRYPTO_CURRENCIES_NEW: "CRYPTO_CURRENCIES_NEW",
  CRYPTO_CURRENCIES_PRESALE: "CRYPTO_CURRENCIES_PRESALE",
  CRYPTO_CURRENCIES_TODAYS_BEST: "CRYPTO_CURRENCIES_TODAYS_BEST",
  CRYPTO_CURRENCIES_TAB: "CRYPTO_CURRENCIES_TAB",
  MOST_VISITED: "MOST_VISITED",
};

export const NFT = {
  NFT_LISTINGS: "NFT_LISTINGS",
};
